package misc;

//constructor, getters, toString(), equals() & hashDode() autogenerated
//can have static fields and methods
//can have instance methods
record Student(String firstName, String lastName, int id) {
    public Student {
        //compact constructor that focuses on business logic
        if (id <= 0) {
            throw new IllegalArgumentException("Id cannot be Zero / Negative");
        }
        firstName = firstName.toLowerCase();
    }
}

public class RecordsDemo {
    public static void main(String[] args) {
        var student1 = new Student("A", "B", 1);
        var student2 = new Student("A", "B", 1);
        System.out.println(student1.equals(student2));
        System.out.println(student1);   //toString() overrident by default
        var student0 = new Student("A", "B", 0);
    }
}
